title: Aniket Panchal
description: Hello there!!, myself Aniket Panchal, am a joyful, foody, humble person who enjoys travelling and exploring places. Also I love to study and watch stuffs about outer space and enjoys gazing the sky through my telescope. I have done Engineering in Electronics and Telecommunication and have been working since the past 5-6 years,
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman
